### ISSUE TITLE
Using in a v-for

### ISSUE THREAD

**Issue by mrbig00** [Gomah/vue-embed#145]
If I'm trying to use it outside of a v-for, it works perfectly otherwise I get the following error:
``` 
Error: You need to pass input element or string in the options object.
```
I'm using the first [example](https://github.com/Gomah/vue-embed#example).

Do you have any suggestions what should I do in order to use it in a v-for?

**Comment by Gomah** [comment]
Hey @mrbig00, do you have a repro example?

Can't see any warning in errors in the console in this example: https://codesandbox.io/s/loving-margulis-s9or3?file=/src/App.vue

**Comment by mrbig00** [comment]
Never mind! It was my bad :)
